from src import scenes

# WINDOW SETTINGS
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500
WINDOW_CAPTION = "OpenGL Coding Practice"
WINDOW_POSITION = (0, 0)

#SCENE SETTINGS
SCENE_FUNCTION = scenes.default_scene
